/* These are the languages that Scratch supports, taken from the scratch-www repository. */

var l10n = {
"Aragonés":"an",
"Asturianu":"ast",
"Bahasa Melayu":"ms",
"Català":"ca",
"Česky":"cs",
"Cymraeg":"cy",
"Dansk":"da",
"Dari":"fa-af",
"Eesti":"et",
"Esperanto":"eo",
"Euskara":"eu",
"Français":"fr",
"Gaeilge":"ga",
"Gàidhlig":"gd",
"Galego":"gl",
"Hrvatski":"hr",
"Íslenska":"is",
"Italiano":"it",
"Kinyarwanda":"rw",
"Kreyòl":"ht",
"Kurdî":"ku",
"Latina":"la",
"Latviešu":"lv",
"Lietuvių":"lt",
"Magyar":"hu",
"Malti":"mt",
"Nederlands":"nl",
"Norsk Bokmål":"nb",
"Oʻzbekcha":"uz",
"Polski":"pl",
"Português":"pt",
"Português Brasileiro":"pt-br",
"Română":"ro",
"Sardu":"sc",
"Slovenčina":"sk",
"Slovenščina":"sl",
"suomi":"fi",
"Svenska":"sv",
"Tepehuan":"nai",
"Tiếng Việt":"vi",
"Аҧсшәа":"ab",
"العربية":"ar",
"Български":"bg",
"Ελληνικά":"el",
"فارسی":"fa",
"עִבְרִית":"he",
"हिन्दी":"hi",
"Հայերեն":"hy",
"日本語":"ja",
"にほんご":"ja-hr",
"សំលៀកបំពាក":"km",
"ಭಾಷೆ-ಹೆಸರು":"kn",
"한국어":"ko",
"Македонски":"mk",
"മലയാളം":"ml",
"Монгол хэл":"mn",
"मराठी":"mr",
"မြန်မာဘာသာ":"my",
"Русский":"ru",
"Српски":"sr",
"ไทย":"th",
"Українська":"uk",
"简体中文":"zh-cn",
"正體中文":"zh-tw"};
